[functions.signup-student]
verify_jwt = false

[functions.signup-volunteer]
verify_jwt = false

[functions.signup-instructor]
verify_jwt = false

[functions.reset-student-password]
verify_jwt = true

[functions.change-student-password]
verify_jwt = true
